#!/bin/sh -e

UNAME_S=`uname -s`
if [ -z "$MAKE" ]; then
	MAKE=make
fi
cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    echo "No need to bootstrap"

    ;;
  configure)
    if [ "`uname -s`" != "Darwin" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's libiconv."
      exit 0
    else
      OPTS="--with-included-gettext --disable-csharp --disable-rpath --disable-libasprintf --disable-static"
    fi
      ./configure $@ $OPTS
    ;;
  make)
    if [ "$UNAME_S" != "Darwin" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's libiconv."
      exit 0
    fi
    $MAKE $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

#vim: ts=2 sw=2 expandtab
