#!/bin/sh

cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list)
    ;;
  bootstrap)
    echo "No need to bootstrap"

    ;;
  configure|make)
    echo "ZWA local compilation not supported, please use the system supplied libiconv"
    exit 1
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
