#!/bin/sh -e

UNAME_S=`uname -s`
if [ -z "$MAKE" ]; then
	MAKE=make
fi
cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list|prepare-dist)
	# fix old and broken libtools, which can't recognise 64 bit windows libs and dlls.
    find -name libtool -o -name ltmain.sh | xargs sed -i -e "s,'file format pe-i386.*\?','file format \(pei\*-i386\(\.\*architecture: i386\)\?|pe-arm-wince|pe-x86-64\)',"
    ;;
  bootstrap)
    echo "No need to bootstrap"

    ;;
  configure)
    if [ "$ZBS_BUILDER_TYPE" != "mingw" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's libiconv."
      exit 0
    else
      OPTS="--with-included-gettext --disable-csharp --disable-rpath --disable-libasprintf --disable-static"
    fi
      ./configure $@ $OPTS
    ;;
  make)
    if [ "$ZBS_BUILDER_TYPE" != "mingw" ]; then
      echo "ZWA local compilation not needed on this platform, using the system's libiconv."
      exit 0
    fi
    $MAKE $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

#vim: ts=2 sw=2 expandtab
